---
abstract: 'Model class for FormHandler using DBIx::Class'
author:
  - 'Gerda Shank'
build_requires:
  DateTime::Format::MySQL: 0
  DateTime::Format::SQLite: 0
  DateTime::Format::W3CDTF: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormHandler-Model-DBIC
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  DBIx::Class::ResultSet::RecursiveUpdate: 0.012
  HTML::FormHandler: 0.30003
  Moose: 0.90
  namespace::autoclean: 0.09
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/gshank/html-formhandler-model-dbic/tree/master
version: 0.10
