---
abstract: 'base class that holds DBIC model role'
author:
  - 'FormHandler Contributors - see HTML::FormHandler'
build_requires:
  DateTime::Format::MySQL: 0
  DateTime::Format::SQLite: 0
  DateTime::Format::W3CDTF: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormHandler-Model-DBIC
requires:
  DBIx::Class: 0
  DBIx::Class::ResultSet::RecursiveUpdate: 0.21
  HTML::FormHandler: 0.34001
  Moose: 2.0007
  namespace::autoclean: 0.09
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=HTML-FormHandler-Model-DBIC
  repository: git://github.com/gshank/html-formhandler-model-dbic.git
version: 0.15
